//an array of people
var queue= [
    { "firstName": "Rita", "lastName": "VonHunty", "passportNumber": "PO098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Persia", "lastName": "Pericles", "passportNumber": "PI098765","priority": "LOW", "status": "", "gender": "UNDEFINED" },
    { "firstName": "Melque", "lastName": "Dalemberg", "passportNumber": "PU098765","priority": "MEDIUM", "status": "", "gender": "MALE" },
    { "firstName": "Lana", "lastName": "Uachausqui", "passportNumber": "PR098765","priority": "HIGH", "status": "", "gender": "FEMALE" },
    { "firstName": "Jose", "lastName": "Gerson", "passportNumber": "PW098765","priority": "LOW", "status": "", "gender": "MALE" },
    { "firstName": "Prince", "lastName": "dasPersia", "passportNumber": "PQ098765","priority": "LOW", "status": "", "gender": "UNDEFINED" },
    { "firstName": "Mario", "lastName": "Maluco", "passportNumber": "PE098765","priority": "HIGH", "status": "", "gender": "MALE" },
    { "firstName": "Mara", "lastName": "Maravilha", "passportNumber": "PZ098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Mercia", "lastName": "Gusmao", "passportNumber": "PX098765","priority": "HIGH", "status": "", "gender": "FEMALE" },
    { "firstName": "Tarugo", "lastName": "Trancoso", "passportNumber": "PC098765","priority": "LOW", "status": "", "gender": "MALE" },
    { "firstName": "Ney", "lastName": "Matogrosso", "passportNumber": "PV098765","priority": "HIGH", "status": "", "gender": "UNDEFINED" },
    { "firstName": "Leila", "lastName": "Diniz", "passportNumber": "PB098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Pedro", "lastName": "Varela", "passportNumber": "PN098765","priority": "LOW", "status": "", "gender": "MALE" },
    { "firstName": "Laila", "lastName": "Leoa", "passportNumber": "PM098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Helio", "lastName": "Militao", "passportNumber": "PP098765","priority": "MEDIUM", "status": "", "gender": "MALE" },
    { "firstName": "Tato", "lastName": "Tantao", "passportNumber": "QO098765","priority": "LOW", "status": "", "gender": "UNDEFINED" },
    { "firstName": "Greta", "lastName": "Parra", "passportNumber": "WO098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Gilberto", "lastName": "Gil", "passportNumber": "EO098765","priority": "HIGH", "status": "", "gender": "MALE" },
    { "firstName": "Maria", "lastName": "DoBairro", "passportNumber": "RO098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Maria", "lastName": "Mercedes", "passportNumber": "TO098765","priority": "LOW", "status": "", "gender": "UNDEFINED" },
    { "firstName": "Sara", "lastName": "Sarada", "passportNumber": "YO098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Mario", "lastName": "Quitana", "passportNumber": "UO098765","priority": "HIGH", "status": "", "gender": "MALE" },
    { "firstName": "Nah", "lastName": "Ozetti", "passportNumber": "AO098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Femma", "lastName": "Kutti", "passportNumber": "SO098765","priority": "MEDIUM", "status": "", "gender": "FEMALE" },
    { "firstName": "Pablo", "lastName": "Neruda", "passportNumber": "FO098765","priority": "LOW", "status": "", "gender": "UNDEFINED" },
    { "firstName": "Sil", "lastName": "Maria", "passportNumber": "GO098765","priority": "MEDIUM", "status": "", "gender": "FEMALE" },
    { "firstName": "Drauzio", "lastName": "Varela", "passportNumber": "VO098765","priority": "LOW", "status": "", "gender": "MALE" },
    { "firstName": "Juanita", "lastName": "Bejamemutcho", "passportNumber": "CO098765","priority": "MEDIUM", "status": "", "gender": "FEMALE" },
    { "firstName": "Joao", "lastName": "Capitao", "passportNumber": "ZO098765","priority": "LOW", "status": "", "gender": "MALE" },
    { "firstName": "Luana", "lastName": "Piovani", "passportNumber": "XO098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Paulinha", "lastName": "Pomerode", "passportNumber": "MO098765","priority": "MEDIUM", "status": "", "gender": "FEMALE" },
    { "firstName": "Bete", "lastName": "Bope", "passportNumber": "NO098765","priority": "LOW", "status": "", "gender": "UNDEFINED" },
    { "firstName": "Luana", "lastName": "Leonor", "passportNumber": "BO098765","priority": "LOW", "status": "", "gender": "FEMALE" },
    { "firstName": "Julia", "lastName": "Lennon", "passportNumber": "JO098765","priority": "MEDIUM", "status": "", "gender": "UNDEFINED" }
];